---
name: "Grafana Alloy"
description: "Grafana Alloy"
version: "0.0.2"
slug: "grafana_alloy"
init: false
arch:
  - aarch64
  - amd64
ports:
  12345/tcp:
ports_description:
  12345/tcp: Alloy web server
map:
  - homeassistant_config
  - share
  - ssl
journald: true
host_network: true
hassio_api: true
homeassistant_api: true
auth_api: true
docker_api: true
host_pid: true

options:
  enable_prometheus: true
  prometheus_write_endpoint: http://prometheus:9090/api/v1/write
  enable_unix_component: true
  enable_process_component: true
  prometheus_scrape_interval: 15s
  servername_tag: "HomeAssistant"
  enable_loki: false
  loki_endpoint: http://loki:3100/api/v1/push
  overrid_config: false
  overide_config_path: "/config/alloy/example.alloy"
schema:
  enable_prometheus: bool
  prometheus_write_endpoint: str?
  enable_unix_component: bool
  enable_process_component: bool
  prometheus_scrape_interval: list(15s|30s|60s)
  servername_tag: str?
  instance_tag: str?
  enable_loki: bool
  loki_endpoint: str?
  overrid_config: bool
  overide_config_path: str?
